### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by bryaan** [Hydrotoast/Avro.jl#6]
```
(v1.1) pkg> add Avro
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Avro [cb912096]:
 Avro [cb912096] log:
 ├─possible versions are: 0.0.1-0.0.3 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-0.0.3
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by bryaan** [comment]
This should be resolved by merging #3

**Comment by Hydrotoast** [comment]
Thanks for identifying this issue @bryaan and thanks to @twadleigh for providing the necessary code changes.

I have not used Julia 1.0+ yet, so please bear with me to resolve this issue. :)

**Update.** After merging #3 , I run the command to add the `Avro` package as you have show:
```
(v1.1) pkg> add Avro
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Avro [cb912096]:
 Avro [cb912096] log:
 ├─possible versions are: 0.0.1-0.0.3 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-0.0.3
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```
Although the PR did not completely resolve this issue, it is necessary to resolve the issue.

**Root cause.** To analyze the root cause, observe that the range of versions between our error outputs have not changed after merging the PR: `0.0.1-0.0.3`. Hence, a new version must be published manually. This is likely a task for me. 

**Plan.** While reviewing the Julia v1.0+ changes, I discovered that the package management system was redesigned. Since this project was last updated with the package management system from Julia v0.6, I plan to change the configuration as necessary, but the build may be unstable in the interim.

_Note._ To avoid breaking any existing clients, I will try to migrate this on a branch. However, I am currently away from home for the next ~4 days; so the update may not be released until then.
